name: Hello World
on: 
  issues:
    types: [edited,labeled]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: NETCore
      uses: ./
      env:
        STATUS_MESSAGE: "This is a message fired from a GitHub Action 🎉 💯"
